# action.yml
name: 'Provenance Action'
description: 'Action to test Provenance and Smart Contracts'
inputs:
  github_token:
    description: 'Github token from the workflow'
    required: true
  provenance_version:  # version of Provenance
    description: 'Version of Provenance to test, either a release or a branch'
    required: true
  test_script:
    description: 'Script used to run tests after provenance has been setup and is running'
    required: false
  generate_proposals:
    description: 'Generate the store, instantiate, and migrate governance proposals'
    required: false
  wasm_path:
    description: 'Path to the smart contract wasm'
    required:  false
runs:
  using: composite
  steps:
    - name: download provenance release
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ inputs.GITHUB_TOKEN }}
        branch: ${{ inputs.provenance_version }}
        repo: provenance-io/provenance
        workflow: release.yml
        workflow_conclusion: success
        name: linux-zip
    - name: run smart contract action
      id: smart-contract-action
      uses: provenance-io/provenance-testing-action/smart-contract-action@v1.1.0
      with:
        test_script: ${{ inputs.test_script }}
        generate_proposals: ${{ inputs.generate_proposals }}
        wasm_path: ${{ inputs.wasm_path }}
    - name: attach artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.job }}_proposals.zip
        path: |
          wasm-store-proposal.json
          instantiate-contract-proposal.json
          migrate-contract-proposal.json
