# action.yml
name: 'Provenance Action'
description: 'Action to test Provenance and Smart Contracts'
inputs:
  github_token:
    description: 'Github token from the workflow'
    required: true
  provenance_version:
    description: 'Version of Provenance to perform test. Either a release or a branch'
    required: true
  smart_contract_action_version:
    description: 'Version of Smart Contract Action to perform test'
    required: false
    default: latest
  init_data:
    description: 'Initial data directory to be used for starting Provenance'
    required: false
  test_script:
    description: 'Script used to run tests after provenance has been setup and is running'
    required: false
  generate_proposals:
    description: 'Generate the store, instantiate, and migrate governance proposals'
    required: false
  wasm_path:
    description: 'Path to the smart contract wasm'
    required:  false
runs:
  using: composite
  steps:
    - name: download provenance release
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ inputs.GITHUB_TOKEN }}
        branch: ${{ inputs.provenance_version }}
        repo: provenance-io/provenance
        workflow: release.yml
        workflow_conclusion: ""
        name: linux-zip
    - name: run smart contract action
      id: smart-contract-action
      shell: bash
      env:
        IMAGE: "provenanceio/smart-contract-action:${{ inputs.smart_contract_action_version }}"
        INIT_DATA: "${{ inputs.init_data != null && inputs.init_data || false }}"
        TEST_SCRIPT: "${{ inputs.test_script != null && inputs.test_script || false }}"
        GENERATE_PROPOSALS: "${{ inputs.generate_proposals }}"
        WASM_PATH: "${{ inputs.wasm_path }}"
      run: |
        docker pull ${{ env.IMAGE }}
        docker run -v $GITHUB_WORKSPACE:/scratch:Z ${{ env.IMAGE }} ${{ env.INIT_DATA }} ${{ env.TEST_SCRIPT }} ${{ env.GENERATE_PROPOSALS }} ${{ env.WASM_PATH }}
    - name: attach artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.job }}_proposals
        path: |
          smart-contract-action/scripts/templates/governance/
