# action.yml
name: 'Smart Contract Action'
description: 'Action to test Smart Contracts with Provenance'
inputs:
  init_data:
    description: 'Initial data directory to be used for starting Provenance'
    required: false
  test_script:
    description: 'Script used to run tests after provenance has been setup and is running'
    required: true
  generate_proposals:
    description: 'Generate the store, instantiate, and migrate governance proposals'
    required: false
  wasm_path:
    description: 'Path to the smart contract wasm'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.init_data != null && inputs.init_data || false }}
    - ${{ inputs.test_script != null && inputs.test_script || false }}
    - ${{ inputs.generate_proposals }}
    - ${{ inputs.wasm_path }}
