name: Smart Contract Action Build Push Test
# Build & Push builds the simapp docker image on every push to master
# and pushes the image to https://hub.docker.com/u/provenanceio
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

# Set concurrency for this workflow to cancel in-progress jobs if retriggered.
# The github.ref is only available when triggered by a PR so fall back to github.run_id for other cases.
# The github.run_id is unique for each run, giving each such invocation it's own unique concurrency group.
# Basically, if you push to a PR branch, jobs that are still running for that PR will be cancelled.
# But jobs started because of a merge to main or a release tag push are not cancelled.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    outputs:
      smart_contract_action_version: ${{ steps.prep.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=provenanceio/smart-contract-action
          VERSION=${{ github.event.pull_request.head.sha }}
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
            if [ "${{ github.event.repository.default_branch }}" = "$VERSION" ]; then
              VERSION=latest
            fi
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          if [[ $VERSION =~ ^v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:${VERSION}"
          fi
          echo "Setting output: version=${VERSION}"
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
          echo "Setting output: tags=${TAGS}"
          echo "tags=${TAGS}" >> "$GITHUB_OUTPUT"
          created="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          echo "Setting output: created=$created"
          echo "created=$created" >> "$GITHUB_OUTPUT"
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: smart-contract-action
          build-args: |
            VERSION=${{ steps.prep.outputs.version }}
          platforms: linux/amd64
          file: smart-contract-action/Dockerfile
          push: true
          tags: ${{ steps.prep.outputs.tags }}

  test_with_provenance_release:
    needs: docker
    runs-on: ubuntu-latest
    name: Test with provenance release with proposals
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Smart Contract Action
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          provenance_version: "v1.16.0"
          smart_contract_action_version: ${{ needs.docker.outputs.smart_contract_action_version }}
          test_script: "./smart-contract-action/test/test.sh"
          generate_proposals: true
          wasm_path: "./smart-contract-action/test/provwasm_tutorial.wasm"

  test_with_provenance_release_no_script:
    needs: docker
    runs-on: ubuntu-latest
    name: Test with provenance release without proposals
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Smart Contract Action
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          provenance_version: "v1.16.0"
          smart_contract_action_version: ${{ needs.docker.outputs.smart_contract_action_version }}
          generate_proposals: true
          wasm_path: "./smart-contract-action/test/provwasm_tutorial.wasm"

  test_with_init_data:
    needs: docker
    runs-on: ubuntu-latest
    name: Test with provenance release without proposals
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Smart Contract Action
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          provenance_version: "v1.16.0"
          smart_contract_action_version: ${{ needs.docker.outputs.smart_contract_action_version }}
          init_data: "./smart-contract-action/test/init_data"
          generate_proposals: true
          wasm_path: "./smart-contract-action/test/provwasm_tutorial.wasm"
